---
sidebar: sidebar 
permalink: faq.html 
keywords: community, forums, help, support, videos, faq, getting help, permissions, access control lists, acls, preserve, preserving, troubleshooting, support, encryption, smb 
summary: フォーラム、チャット サービス、ビデオなどのさまざまなリソースを通じて、 NetApp Copy and Syncに関するサポートを受けたり、詳細情報を入手したりできます。 
---
= NetApp Copy and Sync技術 FAQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
質問に対する簡単な回答を探している場合は、この FAQ が役立ちます。



== 開始

次の質問は、NetApp Copy and Syncの使用開始に関連しています。



=== NetApp Copy and Sync はどのように機能しますか?

コピーと同期では、 NetAppデータ ブローカー ソフトウェアを使用して、ソースからターゲットにデータを同期します (これを _同期関係_ と呼びます)。

データ ブローカー グループは、ソースとターゲット間の同期関係を制御します。同期関係を設定すると、コピーと同期によってソース システムを分析し、複数のレプリケーション ストリームに分割して、選択したターゲット データにプッシュします。

最初のコピーの後、コピーと同期は設定したスケジュールに基づいて変更されたデータを同期します。



=== 14 日間の無料トライアルはどのように機能しますか?

14 日間の無料トライアルは、Copy and Sync にサインアップすると開始されます。作成したコピーおよび同期関係に対しては、14 日間NetApp の料金は発生しません。ただし、デプロイするデータ ブローカーのすべてのリソース料金は引き続き適用されます。



=== コピーと同期にはいくらかかりますか?

コピーと同期の使用に関連するコストには、サービス料金とリソース料金の 2 種類があります。

*サービス料*

従量課金制の場合、コピーおよび同期サービスの料金は、作成する同期関係の数に基づいて時間単位で課金されます。

* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["AWS の従量課金制料金を見る"^]
* https://aws.amazon.com/marketplace/pp/B06XX5V3M2["AWSの年間料金を見る"^]
* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["Azure の価格を見る"^]


コピー ライセンスと同期ライセンスは、 NetApp担当者を通じても入手できます。各ライセンスでは、12 か月間に 20 の同期関係が有効になります。

link:concept-licensing.html["ライセンスについて詳しくはこちら"] 。


NOTE: コピーおよび同期関係は、Azure NetApp Filesでは無料です。

*リソース料金*

リソース料金は、クラウドでデータ ブローカーを実行するためのコンピューティング コストとストレージ コストに関連しています。



=== コピーと同期はどのように請求され、サブスクリプションはどのように管理すればよいですか?

14 日間の無料トライアルが終了した後、同期関係の料金を支払う方法は 2 つあります。最初のオプションは、AWS または Azure からサブスクライブすることです。これにより、従量課金制または年間支払いが可能になります。 2 番目のオプションは、 NetAppから直接ライセンスを購入することです。いずれの場合も、サブスクリプションは、コピーと同期のユーザー インターフェースではなく、プロバイダー マーケットプレイスを通じて管理されます。



=== クラウド外でもコピーと同期を使用できますか?

はい、非クラウド アーキテクチャでもコピーと同期を使用できます。ソースとターゲットはオンプレミスに存在でき、データ ブローカー ソフトウェアも同様にオンプレミスに存在できます。

クラウド外でコピーと同期を使用する場合は、次の重要な点に注意してください。

* データ ブローカー グループは、コピーおよび同期と通信するためにインターネット接続が必要です。
* NetAppから直接ライセンスを購入しない場合は、PAYGO コピーおよび同期の課金のために AWS または Azure アカウントが必要になります。




=== コピーと同期にアクセスするにはどうすればよいですか?

コピーと同期はNetApp Consoleから利用できます。コンソールの左側のナビゲーションから、*モビリティ* > *コピーと同期*を選択します。



=== データ ブローカー グループとは何ですか?

各データ ブローカーはデータ ブローカー グループに属します。データ ブローカーをグループ化すると、同期関係のパフォーマンスが向上します。



== サポートされているソースとターゲット

次の質問は、同期関係でサポートされるソースとターゲットに関連しています。



=== コピーと同期はどのソースとターゲットをサポートしていますか?

コピーと同期は、さまざまな種類の同期関係をサポートします。link:reference-supported-relationships.html["リスト全体を見る"] 。



=== コピーと同期はどのバージョンの NFS と SMB をサポートしていますか?

コピーと同期は、NFS バージョン 3 以降と SMB バージョン 1 以降をサポートしています。

link:reference-requirements.html["同期要件の詳細"] 。



=== Amazon S3 がターゲットの場合、データを特定の S3 ストレージクラスに階層化できますか?

はい、AWS S3 がターゲットの場合は、特定の S3 ストレージ クラスを選択できます。

* 標準（これがデフォルトのクラスです）
* インテリジェントティアリング
* 標準-低頻度アクセス
* 1つのゾーン - 低頻度アクセス
* グレイシャーディープアーカイブ
* 氷河フレキシブルリトリーバル
* 氷河の即時検索




=== Azure Blob ストレージのストレージ層はどうですか?

BLOB コンテナーがターゲットの場合は、特定の Azure BLOB ストレージ層を選択できます。

* ホットストレージ
* クールストレージ




=== Google Cloud のストレージ階層をサポートしていますか?

はい、Google Cloud Storage バケットがターゲットの場合は、特定のストレージ クラスを選択できます。

* Standard
* ニアライン
* コールドライン
* アーカイブ




== ネットワーク

次の質問は、コピーと同期のネットワーク要件に関連しています。



=== コピーと同期のネットワーク要件は何ですか?

コピーおよび同期環境では、データ ブローカー グループが、選択したプロトコルまたはオブジェクト ストレージ API (Amazon S3、Azure Blob、IBM Cloud Object Storage) を介してソースおよびターゲットに接続されている必要があります。

さらに、データ ブローカー グループには、Copy and Sync と通信し、他のいくつかのサービスやリポジトリに接続できるように、ポート 443 経由の送信インターネット接続が必要です。

詳細については、link:reference-networking.html["ネットワーク要件を確認する"] 。



=== データ ブローカーでプロキシ サーバーを使用できますか?

○

コピーと同期は、基本認証の有無にかかわらずプロキシ サーバーをサポートします。データ ブローカーをデプロイするときにプロキシ サーバーを指定すると、データ ブローカーからのすべての HTTP および HTTPS トラフィックはプロキシ経由でルーティングされます。  NFS や SMB などの非 HTTP トラフィックはプロキシ サーバー経由でルーティングできないことに注意してください。

プロキシ サーバーの唯一の制限は、NFS またはAzure NetApp Files の同期関係でデータインフライト暗号化を使用する場合です。暗号化されたデータは HTTPS 経由で送信され、プロキシ サーバー経由でルーティングすることはできません。



== データ同期

次の質問は、データ同期の仕組みに関するものです。



=== 同期はどのくらいの頻度で行われますか?

デフォルトのスケジュールは毎日同期するように設定されています。最初の同期後に、次の操作を実行できます。

* 同期スケジュールを希望の日数、時間、分数に変更します
* 同期スケジュールを無効にする
* 同期スケジュールを削除します（データは失われず、同期関係のみが削除されます）




=== 最小同期スケジュールは何ですか?

関係を 1 分ごとに同期するようにスケジュールできます。



=== ファイルの同期に失敗した場合、データ ブローカー グループは再試行しますか? それともタイムアウトになりますか?

1 つのファイルの転送に失敗しても、データ ブローカー グループはタイムアウトしません。代わりに、データ ブローカー グループは、ファイルをスキップする前に 3 回再試行します。再試行値は、同期関係の設定で構成できます。

link:task-managing-relationships.html#change-the-settings-for-a-sync-relationship["同期関係の設定を変更する方法を学ぶ"] 。



=== データセットが非常に大きい場合はどうすればよいですか?

1つのディレクトリに600,000以上のファイルが含まれている場合、link:task-get-help.html["お問い合わせ"]ペイロードを処理するためのデータ ブローカー グループの構成を支援できるようになります。データ ブローカー グループに追加のメモリを追加する必要がある可能性があります。

マウント ポイント内のファイルの総数には制限がないことに注意してください。階層のレベル (最上位ディレクトリまたはサブディレクトリ) に関係なく、600,000 個以上のファイルを含む大規模なディレクトリには追加のメモリが必要です。



== セキュリティ

以下の質問はセキュリティに関するものです。



=== コピーと同期は安全ですか?

○すべてのコピーと同期のネットワーク接続は、 https://aws.amazon.com/sqs/["Amazon シンプルキューサービス (SQS)"^] 。

データブローカー グループと Amazon S3、Azure Blob、Google Cloud Storage、IBM Cloud Object Storage 間のすべての通信は、HTTPS プロトコルを介して行われます。

オンプレミス (ソースまたは宛先) システムでコピーと同期を使用している場合は、次の接続オプションが推奨されます。

* インターネットを経由しないルーティング（指定したクラウド ネットワークとのみ通信可能）である AWS Direct Connect、Azure ExpressRoute、または Google Cloud Interconnect 接続
* オンプレミスのゲートウェイデバイスとクラウドネットワーク間のVPN接続
* S3 バケット、Azure Blob ストレージ、または Google Cloud Storage を使用したデータ転送の安全性をさらに高めるには、Amazon プライベート S3 エンドポイント、Azure 仮想ネットワーク サービス エンドポイント、またはプライベート Google アクセスを確立できます。


これらの方法はいずれも、オンプレミスの NAS サーバーとコピーおよび同期データ ブローカー グループ間の安全な接続を確立します。



=== コピーと同期によってデータは暗号化されますか?

* コピーと同期は、ソース NFS サーバーとターゲット NFS サーバー間のデータインフライト暗号化をサポートします。link:task-nfs-encryption.html["詳細情報"] 。
* SMB の場合、コピーと同期は、サーバー側で暗号化された SMB 3.0 および 3.11 データをサポートします。コピーと同期は、暗号化されたデータをソースからターゲットにコピーし、データは暗号化されたままになります。
+
コピーと同期では、SMB データ自体を暗号化することはできません。

* Amazon S3 バケットが同期関係のターゲットである場合、AWS KMS 暗号化または AES-256 暗号化を使用してデータ暗号化を有効にするかどうかを選択できます。
* Google ストレージ バケットが同期関係のターゲットである場合、デフォルトの Google 管理の暗号化キーを使用するか、独自の KMS キーを使用するかを選択できます。




== 権限

次の質問はデータの権限に関するものです。



=== SMB データ権限はターゲットの場所に同期されていますか?

コピーと同期を設定すると、ソース SMB 共有とターゲット SMB 共有間、およびソース SMB 共有からオブジェクト ストレージ ( ONTAP S3 を除く) へのアクセス制御リスト (ACL) を保持できます。


NOTE: コピーと同期では、オブジェクト ストレージから SMB 共有への ACL のコピーはサポートされていません。

link:task-copying-acls.html["SMB共有間でACLをコピーする方法を学ぶ"] 。



=== NFS データの権限はターゲットの場所に同期されていますか?

コピーと同期は、次のように NFS サーバー間で NFS 権限を自動的にコピーします。

* NFS バージョン 3: コピーと同期は、権限とユーザー グループの所有者をコピーします。
* NFS バージョン 4: コピーと同期は ACL をコピーします。




== オブジェクトストレージメタデータ



=== どのような同期関係がオブジェクト ストレージ メタデータを保存しますか?

コピーと同期は、次の種類の同期関係について、オブジェクト ストレージ メタデータをソースからターゲットにコピーします。

* Amazon S3 -> Amazon S3 ^1^
* Amazon S3 ->StorageGRID
* StorageGRID-> Amazon S3
* StorageGRID->StorageGRID
* StorageGRID -> Google Cloud Storage
* Google Cloud Storage -> StorageGRID ^1^
* Google Cloud Storage -> IBM Cloud オブジェクト ストレージ ^1^
* Google クラウド ストレージ -> Amazon S3 ^1^
* Amazon S3 -> Google クラウド ストレージ
* IBM Cloud オブジェクト ストレージ -> Google Cloud ストレージ
* StorageGRID -> IBM Cloud オブジェクトストレージ
* IBM Cloud オブジェクトストレージ -> StorageGRID
* IBM Cloud オブジェクト ストレージ -> IBM Cloud オブジェクト ストレージ


^1^ これらの同期関係では、link:task-creating-relationships.html["同期関係を作成するときにオブジェクトのコピー設定を有効にします"] 。



=== NFS または SMB がソースである場合の同期中に、どのような種類のメタデータが複製されますか?

ユーザー ID、変更時刻、アクセス時刻、GID などのメタデータはデフォルトで複製されます。ユーザーは、同期関係を作成するときに ACL を必須としてマークすることにより、CIF から ACL を複製することを選択できます。



== パフォーマンス

次の質問は、コピーと同期のパフォーマンスに関するものです。



=== 同期関係の進行状況インジケーターは何を表していますか?

同期関係には、データ ブローカー グループのネットワーク アダプターのスループットが表示されます。複数のデータ ブローカーを使用して同期パフォーマンスを高速化した場合、スループットはすべてのトラフィックの合計になります。このスループットは 20 秒ごとに更新されます。



=== パフォーマンスの問題が発生しています。同時転送の数を制限することはできますか?

ファイルが非常に大きい場合 (それぞれ複数 TiB)、転送プロセスの完了に長い時間がかかり、パフォーマンスに影響が出る可能性があります。

同時転送の数を制限すると役立ちます。link:task-get-help.html["ヘルプが必要な場合はお問い合わせください"] 。



=== Azure NetApp Filesのパフォーマンスが低下するのはなぜですか?

Azure NetApp Filesとの間でデータを同期する場合、ディスク サービス レベルが Standard の場合は障害やパフォーマンスの問題が発生する可能性があります。

同期パフォーマンスを向上させるには、サービス レベルを Premium または Ultra に変更します。

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-service-levels#throughput-limits["Azure NetApp Files のサービス レベルとスループットの詳細"^] 。



=== グループには何人のデータ ブローカーが必要ですか?

新しい関係を作成するときは、グループ内の単一のデータ ブローカーから開始します (高速同期関係に属する既存のデータ ブローカーを選択した場合を除く)。多くの場合、単一のデータ ブローカーで同期関係のパフォーマンス要件を満たすことができます。そうでない場合は、グループにデータ ブローカーを追加することで同期のパフォーマンスを向上できます。ただし、まず同期パフォーマンスに影響を与える可能性のある他の要因を確認する必要があります。

データ転送のパフォーマンスには複数の要因が影響する可能性があります。全体的な同期パフォーマンスは、ネットワーク帯域幅、待ち時間、ネットワーク トポロジ、およびデータ ブローカー VM の仕様とストレージ システムのパフォーマンスによって影響を受ける可能性があります。たとえば、グループ内の単一のデータ ブローカーは 100 MB/秒に到達できますが、ターゲットのディスク スループットは 64 MB/秒しか許可されない場合があります。その結果、データ ブローカー グループはデータのコピーを試行し続けますが、ターゲットはデータ ブローカー グループのパフォーマンスを満たすことができません。

したがって、ネットワークのパフォーマンスとターゲット上のディスク スループットを必ず確認してください。

次に、グループにデータ ブローカーを追加してその関係の負荷を分散し、同期パフォーマンスを高速化することを検討できます。link:task-managing-relationships.html#accelerate-sync-performance["同期パフォーマンスを高速化する方法を学ぶ"] 。



== 削除する

次の質問は、ソースとターゲットから同期関係とデータを削除することに関するものです。



=== コピーと同期の関係を削除するとどうなりますか?

関係を削除すると、今後のすべてのデータ同期が停止され、支払いが終了します。ターゲットに同期されたデータはそのまま残ります。



=== ソースサーバーから何かを削除するとどうなりますか? ターゲットからも削除されますか?

デフォルトでは、アクティブな同期関係がある場合、ソース サーバーで削除された項目は、次回の同期時にターゲットから削除されません。ただし、各関係の同期設定にはオプションがあり、ソースからファイルが削除された場合にコピーと同期によってターゲットの場所にあるファイルも削除するように定義できます。

link:task-managing-relationships.html#change-the-settings-for-a-sync-relationship["同期関係の設定を変更する方法を学ぶ"] 。



=== ターゲットから何かを削除するとどうなりますか? 私のソースからも削除されましたか?

アイテムがターゲットから削除されても、ソースからは削除されません。関係はソースからターゲットへの一方向です。次の同期サイクルでは、コピーと同期によってソースとターゲットが比較され、アイテムが不足していることが識別され、コピーと同期によってそのアイテムがソースからターゲットに再度コピーされます。



== トラブルシューティング

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Sync/Cloud_Sync_FAQ:_Support_and_Troubleshooting["NetAppナレッジベース: コピーと同期に関する FAQ: サポートとトラブルシューティング"^]



== データブローカーの詳細

次の質問はデータ ブローカーに関するものです。



=== データブローカーのアーキテクチャについて説明していただけますか?

もちろん。最も重要なポイントは次のとおりです。

* データ ブローカーは、Linux ホスト上で実行される node.js アプリケーションです。
* コピーと同期は、データ ブローカーを次のように展開します。
+
** AWS: AWS CloudFormation テンプレートから
** Azure: Azure リソース マネージャーから
** Google: Google Cloud Deployment Manager から
** 独自のLinuxホストを使用する場合は、ソフトウェアを手動でインストールする必要があります。


* データ ブローカー ソフトウェアは自動的に最新バージョンにアップグレードされます。
* データブローカーは、信頼性が高く安全な通信チャネルとして、また制御と監視のために AWS SQS を使用します。  SQS は永続性レイヤーも提供します。
* 転送速度を向上させ、高可用性を高めるために、グループにデータ ブローカーを追加できます。  1 つのデータ ブローカーに障害が発生した場合でも、サービスの回復力は確保されます。

