---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: 14 日間の無料トライアルが終了した後、同期関係の料金を支払う方法は 2 つあります。最初のオプションは従量課金制です。  2 番目のオプションは、 NetAppから直接ライセンスを購入することです。 
---
= NetApp Copy and Syncの無料トライアル期間終了後は、同期関係の料金が発生します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Copy and Syncの 14 日間の無料トライアルが終了した後、同期関係の支払い方法は 2 つあります。最初のオプションは、AWS または Azure から従量課金制または年間払いでサブスクライブすることです。  2 番目のオプションは、 NetAppから直接ライセンスを購入することです。

AWS Marketplace または Azure Marketplace からサブスクライブできます。両方から購読することはできません。

マーケットプレイス サブスクリプションでNetAppのライセンスを使用するオプションがあります。たとえば、同期関係が 25 個ある場合、ライセンスを使用して最初の 20 個の同期関係に対して料金を支払い、残りの 5 個の同期関係については AWS または Azure から従量課金制で支払うことができます。

link:concept-licensing.html["ライセンスの仕組みについて詳しくはこちら"] 。

無料トライアル終了後すぐにお支払いいただけない場合、追加の関係を作成することはできません。既存の関係は削除されませんが、サブスクライブするかライセンスを入力するまで、変更することはできません。

ライセンスは、 NetApp Consoleサブスクリプションではなく、 NetApp Copy and Syncまたは該当する Web サイトを通じて管理する必要があります。



== [[aws]]AWSからサブスクライブ

AWS では従量課金制または年間払いを選択できます。

.従量課金制への手順
. NetApp Consoleのナビゲーション メニューから、*Mobility > Copy and Sync* を選択します。
. *ライセンス*を選択します。
. 「AWS」を選択します。
. *サブスクライブ*を選択し、*続行*を選択します。
. AWS Marketplace からサブスクライブし、Copy and Sync に再度ログインして登録を完了します。
+
次のビデオでそのプロセスが示されています。

+
.AWS Marketplaceからコピーと同期をサブスクライブする
video::796ffd6d-cade-4750-8504-b24c010b225d[panopto]


.年間支払いの手順
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["AWSマーケットプレイスのページへ"^] 。
. *購読を続ける*を選択します。
. 契約オプションを選択し、「契約の作成」を選択します。




== [[azure]]Azureからサブスクライブ

Azure では、従量課金制または年間支払いを選択できます。

.要件
関連するサブスクリプションで共同作成者または所有者のアクセス許可を持つ Azure ユーザー アカウント。

.手順
. NetApp Consoleのナビゲーション メニューから、*Mobility > Copy and Sync* を選択します。
. *ライセンス*を選択します。
. *Azure* を選択します。
. *サブスクライブ*を選択し、*続行*を選択します。
. Azure ポータルで、[作成] を選択し、オプションを選択して、[サブスクライブ] を選択します。
+
時間ごとに支払う場合は「*月払い*」、1 年分を前払いする場合は「*年払い*」を選択します。

. デプロイが完了したら、通知ポップアップで SaaS リソースの名前を選択します。
. *アカウントの設定*を選択して、コピーと同期に戻ります。
+
次のビデオでそのプロセスが示されています。

+
.Azure Marketplace からコピーと同期をサブスクライブする
video::a6a39447-b7b1-42f6-9c89-b24c010b21b9[panopto]




== [[ライセンス]] NetAppからライセンスを購入し、コピーと同期に追加します

同期関係の料金を前払いするには、1 つ以上のライセンスを購入し、それをコピーと同期に追加する必要があります。

.要件
ライセンスのシリアル番号と、ライセンスが関連付けられているNetAppサポート サイト アカウントのユーザー名とパスワードが必要になります。

.手順
. ライセンスを購入するには、mailto:ng-cloudsync-contact@netapp.com?subject=Cloud%20Sync%20Service%20-%20BYOL%20License%20Purchase%20Request[ NetAppへのお問い合わせ] にメールを送信してください。
. link:task-login-copyandsync.html["コピーと同期にログイン"] 。
. *ライセンス*を選択します。
. *ライセンスの追加*を選択し、必要な情報を追加します。
+
.. シリアル番号を入力してください。
.. 追加するライセンスに関連付けられているNetAppサポート サイト アカウントを選択します。
+
*** アカウントがすでにNetApp Consoleに追加されている場合は、ドロップダウン リストから選択します。
*** アカウントがまだ追加されていない場合は、[*NSS 資格情報の追加*] を選択し、ユーザー名とパスワードを入力して、[*登録*] を選択し、ドロップダウン リストから選択します。


.. *追加*を選択します。






== ライセンスを更新する

NetAppから購入したコピーおよび同期ライセンスを延長した場合、コピーおよび同期で新しい有効期限は自動的に更新されません。有効期限を更新するには、ライセンスを再度追加する必要があります。ライセンスは、 NetApp Consoleサブスクリプションではなく、Copy and Sync または該当する Web サイトを通じて管理する必要があります。

.手順
. NetApp Consoleのナビゲーション メニューから、*Mobility > Copy and Sync* を選択します。
. *ライセンス*を選択します。
. *ライセンスの追加*を選択し、必要な情報を追加します。
+
.. シリアル番号を入力してください。
.. 追加するライセンスに関連付けられているNetAppサポート サイト アカウントを選択します。
.. *追加*を選択します。




.結果
コピーと同期により、既存のライセンスが新しい有効期限で更新されます。
